name: snail-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - affine
  - black
  - geopandas
  - jupyter
  - matplotlib
  - nbstripout
  - networkx
  - numpy
  - openpyxl
  - pandera
  - pip
  - pyarrow
  - pytest
  - pytest-cov
  - rasterio
  - seaborn
  - shapely
  - scipy
  - pip:
    - hilbertcurve
    - irv_autopkg_client
    - python-igraph
    - snkit
    - tqdm
