name: snail-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - affine
  - black
  - geopandas
  - nbstripout
  - numpy
  - pip
  - pytest
  - pytest-cov
  - rasterio
  - shapely
  - pip:
    - python-igraph
